# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d77a43fa069b6eeb0c6cf25da084bc51fda8877137d283bf3a699495f43b742b94ccd1c3f671fc62073a3254d07ede44e436e8dea6b4d0fd290b23cc9b2fa5cf

test:
  secret_key_base: fd400df73921c368fe825b3e78195fc6a8fbf677f3d7fcc41b79a1bdcd756defe056b019f4051119ee04531eb005e093f971519b0ef7346d3aaf9ef9781ffa03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
